services:
  - type: web
    name: marketplayground-backend
    env: python
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/main.py
    pythonVersion: 3.9.13
    envVars:
      - key: ENV
        value: production
