# backend/app.py

from fastapi import FastAPI
from schemas import BeliefRequest  # ✅ This enables FastAPI to understand the input schema
from ai_engine.ai_engine import run_ai_engine
from feedback_handler import submit_feedback, predict_feedback

app = FastAPI()


@app.get("/")
def root():
    return {"message": "MarketPlayground API is live."}


@app.post("/process_belief")
def process_belief(request: BeliefRequest):
    """
    Accepts a natural language belief from the user and returns
    a strategy generated by the AI engine.
    
    Example Input: {"belief": "TSLA will go up this week"}
    """
    return run_ai_engine(request.belief)


@app.post("/submit_feedback")
def submit_feedback_endpoint(feedback: dict):
    """
    Submits feedback to improve future model training.
    """
    return submit_feedback(feedback)


@app.post("/predict_feedback")
def predict_feedback_endpoint(request: dict):
    """
    Predicts a label based on the submitted feedback input.
    """
    return predict_feedback(request)
